version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: admin      
      DB_RESET_ON_SERVER_START: "false"
    ports:
      - 4001:4001
    depends_on:
      - db      
  
  
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bin_rental
      MARIADB_DATABASE: bin_rental
      MYSQL_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - 3306:3306      


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 4010:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db


  adminer:
    image: adminer
    restart: always
    ports:
      - 4020:8080      

volumes:
  mariadb-data: